import type { KitPageData, TemplateId } from "@/store/kitPage";

/** Fully populated demo creator used for marketing/app template previews. */
export function buildDemoCreator(template: TemplateId): KitPageData {
  return {
    slug: "alexrivera-demo",
    template,
    displayName: "Alex Rivera",
    tagline: "Honest reviews. Real engagement. Built for brand stories.",
    bio: "I'm Alex — I make tech and lifestyle content brands trust. Three years of consistent uploads, real engagement, and partnerships with DTC teams who care about authentic storytelling.",
    profileImage: null,
    bannerImage: null,
    bannerVideo: null,
    nicheTags: ["Tech", "Lifestyle", "Reviews"],
    location: "Lagos, Nigeria",
    languages: ["English", "Yoruba"],
    creatingSince: 2022,
    collabStyle: "I specialize in honest, story-led product reviews for DTC brands.",
    platforms: [
      {
        id: "demo_tt",
        platform: "tiktok",
        handle: "@alexrivera",
        followers: 1_800_000,
        avgViews: 240_000,
        engagementRate: 6.4,
        visible: true,
        selfReported: false,
        label: "Main",
        labelChangedAt: null,
      },
      {
        id: "demo_ig",
        platform: "instagram",
        handle: "@alex.rivera",
        followers: 412_000,
        avgViews: 58_000,
        engagementRate: 4.1,
        visible: true,
        selfReported: false,
        label: "Main",
        labelChangedAt: null,
      },
      {
        id: "demo_yt",
        platform: "youtube",
        handle: "@AlexRivera",
        followers: 96_400,
        avgViews: 22_000,
        engagementRate: 5.2,
        visible: true,
        selfReported: false,
        label: "Main",
        labelChangedAt: null,
      },
    ],
    contentGallery: [
      {
        id: "dc1",
        platform: "tiktok",
        url: "https://www.tiktok.com/@alexrivera/video/1",
        caption: "iPhone 17 Pro vs Pixel 9 — honest take.",
        featured: true,
        views: 1_240_000,
        likes: 142_000,
        engagementRate: 11.4,
        selfReported: false,
        niche: "Tech",
      },
      {
        id: "dc2",
        platform: "instagram",
        url: "https://instagram.com/p/2",
        caption: "Skincare routine that actually works.",
        featured: false,
        views: 312_000,
        likes: 38_000,
        engagementRate: 12.2,
        selfReported: false,
        niche: "Lifestyle",
      },
    ],
    brandCollabs: [
      { id: "db1", brandName: "Glossier", logoUrl: null, deliverables: "2 IG Reels, 1 TikTok", results: "1.4M reach, 84K saves" },
      { id: "db2", brandName: "Notion", logoUrl: null, deliverables: "YouTube long-form, IG carousel", results: "320K views, 6.1% CTR" },
    ],
    testimonials: [
      {
        id: "dt1",
        quote: "Alex delivered above expectations. Engagement was real and the brand story landed perfectly.",
        reviewerName: "Maya Chen",
        brandName: "Glossier",
        rating: 5,
        verified: true,
        visible: true,
        status: "approved",
        brandLogoUrl: null,
      },
      {
        id: "dt2",
        quote: "One of the cleanest creator collabs we've run this year.",
        reviewerName: "Jordan P.",
        brandName: "Notion",
        rating: 5,
        verified: true,
        visible: true,
        status: "approved",
        brandLogoUrl: null,
      },
    ],
    rates: {
      isPublic: true,
      rows: [
        { id: "dr1", platform: "tiktok", deliverable: "TikTok 60s", priceUSD: 2400, notes: "Includes 1 round of revisions." },
        { id: "dr2", platform: "instagram", deliverable: "Instagram Reel + 1 Story", priceUSD: 1800, notes: "Whitelist available." },
      ],
      licensingNotes: "Organic usage only. Paid usage quoted separately.",
      turnaround: "5–7 business days",
    },
    inquirySettings: {
      introMessage: "Tell me about your brand and what you're trying to launch.",
      showBudgetField: true,
    },
    seo: { title: "Alex Rivera — Demo Kit", description: "Demo creator kit page", ogImageUrl: null },
    audience: {
      primaryAge: "25-34",
      genderSplit: { female: 58, male: 38, other: 4 },
      topCountry: "NG",
      secondaryCountry: "US",
      isVerified: false,
    },
    isActive: true,
    passwordProtect: false,
    passphrase: "",
    countryRestrictions: [],
    contactEmail: "alex@kitpager.pro",
  };
}
